import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { createId, getDatabase, getRequestContext, isoNow, meta } from "@/server/http/context";

const Schema = z.object({ name: z.string().min(1), targetAmount: z.string().min(1), targetDate: z.string().nullable().optional(), horizon: z.enum(["SHORT", "MEDIUM", "LONG"]), priority: z.string().min(1), assetPreference: z.string().nullable().optional() });

export async function POST(req: NextRequest) { const parsed = Schema.safeParse(await req.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: { code: "INVALID_REQUEST", message: "Invalid goal", details: parsed.error.format() } }, { status: 400 }); const now=isoNow(); const db=getDatabase(); const id=createId("goal"); db.prepare("INSERT INTO goals (id,user_id,name,target_amount_decimal,target_date,horizon,priority,asset_preference,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)").run(id,getRequestContext(req).userId,parsed.data.name,parsed.data.targetAmount,parsed.data.targetDate??null,parsed.data.horizon,parsed.data.priority,parsed.data.assetPreference??null,now,now); const row=db.prepare("SELECT * FROM goals WHERE id=?").get(id); db.close(); return NextResponse.json({data:formatGoal(row as Record<string,unknown>),meta:meta()},{status:201}); }
export async function GET(req: NextRequest) { const db=getDatabase(); const rows=db.prepare("SELECT * FROM goals WHERE user_id=? AND status='active' ORDER BY created_at DESC").all(getRequestContext(req).userId) as Array<Record<string,unknown>>; db.close(); return NextResponse.json({data:{items:rows.map(formatGoal)},meta:meta()}); }
function formatGoal(row:Record<string,unknown>){return{id:row.id,name:row.name,targetAmount:row.target_amount_decimal,targetDate:row.target_date,horizon:row.horizon,priority:row.priority,assetPreference:row.asset_preference,status:String(row.status).toUpperCase(),version:row.version,createdAt:row.created_at,updatedAt:row.updated_at};}
