import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";

import { createId, getDatabase, getRequestContext, isoNow, meta } from "@/server/http/context";

const Schema = z.object({ clientMessageId: z.string().max(128).optional(), content: z.string().min(1).max(4000), outputMode: z.enum(["SQL_ONLY", "CHART", "FINANCIAL_REPORT"]).optional() });

export async function GET(req: NextRequest, { params }: { params: Promise<{ id: string }> }) { const { id } = await params; const db = getDatabase(); const owns = db.prepare("SELECT id FROM conversation_sessions WHERE id=? AND user_id=?").get(id, getRequestContext(req).userId); if (!owns) { db.close(); return NextResponse.json({ error: { code: "RESOURCE_NOT_FOUND", message: "Conversation not found" } }, { status: 404 }); } const rows = db.prepare("SELECT * FROM messages WHERE session_id=? ORDER BY created_at ASC").all(id); db.close(); return NextResponse.json({ data: { items: rows }, meta: meta() }); }

export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) { const { id } = await params; const parsed = Schema.safeParse(await req.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: { code: "VALIDATION_ERROR", message: "Invalid message", details: parsed.error.format() } }, { status: 422 }); const db = getDatabase(); const userId = getRequestContext(req).userId; const session = db.prepare("SELECT id FROM conversation_sessions WHERE id=? AND user_id=? AND status='active'").get(id, userId); if (!session) { db.close(); return NextResponse.json({ error: { code: "RESOURCE_NOT_FOUND", message: "Conversation not found" } }, { status: 404 }); } const now = isoNow(); const messageId = createId("message"); db.prepare("INSERT INTO messages (id,session_id,role,content,created_at) VALUES (?,?,?,?,?)").run(messageId, id, "user", parsed.data.content, now); db.prepare("UPDATE conversation_sessions SET updated_at=? WHERE id=?").run(now, id); const analysisId = createId("analysis"); db.prepare("INSERT INTO agent_runs (id,user_id,type,status,created_at) VALUES (?,?,?,?,?)").run(analysisId, userId, "conversation_agent", "queued", now); db.close(); return NextResponse.json({ data: { messageId, analysis: { analysisId, type: "ADVISORY", status: "QUEUED", streamUrl: `/api/v1/analyses/${analysisId}/events` }, outputMode: parsed.data.outputMode ?? "SQL_ONLY" }, meta: meta() }, { status: 202 }); }
