import { NextRequest, NextResponse } from "next/server";

import { createId, getDatabase, getRequestContext, isoNow, meta } from "@/server/http/context";

function mode(value: unknown): "SQL_ONLY" | "CHART" | "FINANCIAL_REPORT" { return value === "CHART" || value === "FINANCIAL_REPORT" ? value : "SQL_ONLY"; }

export async function GET(req: NextRequest, { params }: { params: Promise<{ id: string }> }) { const { id } = await params; const db = getDatabase(); const owns = db.prepare("SELECT id FROM conversation_sessions WHERE id=? AND user_id=?").get(id, getRequestContext(req).userId); if (!owns) { db.close(); return NextResponse.json({ error: { code: "RESOURCE_NOT_FOUND", message: "Conversation not found" } }, { status: 404 }); } const row = db.prepare("SELECT * FROM conversation_output_preferences WHERE session_id=? AND user_id=?").get(id, getRequestContext(req).userId) as Record<string, unknown> | undefined; db.close(); return NextResponse.json({ data: { conversationId: id, configuredMode: row ? mode(String(row.output_mode).toUpperCase()) : null, effectiveMode: row ? mode(String(row.output_mode).toUpperCase()) : "SQL_ONLY", version: row?.row_version ?? 0 }, meta: meta() }); }

export async function PUT(req: NextRequest, { params }: { params: Promise<{ id: string }> }) { const { id } = await params; const body = await req.json().catch(() => null) as { outputMode?: string } | null; if (!body?.outputMode || !["SQL_ONLY", "CHART", "FINANCIAL_REPORT"].includes(body.outputMode)) return NextResponse.json({ error: { code: "VALIDATION_ERROR", message: "Unsupported output mode" } }, { status: 422 }); const db = getDatabase(); const userId = getRequestContext(req).userId; const owns = db.prepare("SELECT id FROM conversation_sessions WHERE id=? AND user_id=?").get(id, userId); if (!owns) { db.close(); return NextResponse.json({ error: { code: "RESOURCE_NOT_FOUND", message: "Conversation not found" } }, { status: 404 }); } const current = db.prepare("SELECT row_version FROM conversation_output_preferences WHERE session_id=?").get(id) as { row_version?: number } | undefined; if (current && !req.headers.get("If-Match")) { db.close(); return NextResponse.json({ error: { code: "VERSION_CONFLICT", message: "If-Match required", details: { currentVersion: current.row_version } } }, { status: 412 }); } const now = isoNow(); db.prepare(`INSERT INTO conversation_output_preferences (id,session_id,user_id,output_mode,created_at,updated_at,row_version) VALUES (?,?,?,?,?,?,1) ON CONFLICT(session_id) DO UPDATE SET output_mode=excluded.output_mode,updated_at=excluded.updated_at,row_version=conversation_output_preferences.row_version+1`).run(createId("pref"), id, userId, body.outputMode.toLowerCase(), now, now); const row = db.prepare("SELECT row_version FROM conversation_output_preferences WHERE session_id=?").get(id) as { row_version: number }; db.close(); return NextResponse.json({ data: { conversationId: id, configuredMode: body.outputMode, effectiveMode: body.outputMode, version: row.row_version }, meta: meta() }); }

export async function DELETE(req: NextRequest, { params }: { params: Promise<{ id: string }> }) { const { id } = await params; const db = getDatabase(); const result = db.prepare("DELETE FROM conversation_output_preferences WHERE session_id=? AND user_id=?").run(id, getRequestContext(req).userId); db.close(); return new Response(null, { status: result.changes >= 0 ? 204 : 404 }); }
